---

- name: Ensure SimpleSamlPhp (PHP SAML library) installed
  git:
    repo: https://github.com/simplesamlphp/simplesamlphp.git
    dest: "{{ m_simplesamlphp_path }}"
    version: "tags/v1.15.0"
  tags:
    - latest

- name: Ensure SimpleSamlAuth (MediaWiki extension) installed
  git:
    # Main version of this extension, jornane/mwSimpleSamlAuth, is slow to
    # update. Use this fork instead, which should stay current with jornane
    # until meza switches to Cicalese's Extension:SimpleSamlPhp.
    repo: https://github.com/jamesmontalvo3/mwSimpleSamlAuth.git
    dest: "{{ m_mediawiki }}/extensions/SimpleSamlAuth"
    version: master
  tags:
    - latest

- name: Ensure simplesamlphp dependencies in place
  composer:
    command: install
    working_dir: "{{ m_simplesamlphp_path }}"

- name: Ensure config files in place
  template:
    src: "{{ item.filename }}.j2"
    dest: "{{ item.dest_path }}/{{ item.filename }}"
  with_items:

    # Config files for SimpleSamlPhp (PHP SAML library)
    - filename: "config.php"
      dest_path: "{{ m_simplesamlphp_path }}/config"
    - filename: "saml20-idp-remote.php"
      dest_path: "{{ m_simplesamlphp_path }}/metadata"
    - filename: "authsources.php"
      dest_path: "{{ m_simplesamlphp_path }}/config"

    # Config files for SimpleSamlAuth (MediaWiki extension)
    - filename: "samlLocalSettings.php"
      dest_path: "{{ m_deploy }}"

    # Config file used by MW extension + any other PHP app needing auth
    # (landing page, admin functions, etc)
    - filename: "SAMLConfig.php"
      dest_path: "{{ m_deploy }}"

- name: Ensure NonMediaWikiSimpleSamlAuth.php in place
  copy:
    src: files/NonMediaWikiSimpleSamlAuth.php
    dest: "{{ m_htdocs }}/NonMediaWikiSimpleSamlAuth.php"
    owner: root
    group: root
    mode: 0755
