---
# run with:
# cd /opt/meza/ansible
# sudo -u meza-ansible ansible-playbook site.yml

# FIXME #729: Move this into a role
- hosts: localhost
  become: yes
  vars:
    m_home: "/opt/conf-meza/users"
  tasks:
  - name: Ensure no password on meza-ansible user on controller
    shell: passwd --delete meza-ansible
    ignore_errors: yes

  - name: Ensure controller has user alt-meza-ansible
    user:
      name: alt-meza-ansible
      move_home: yes
      home: "{{ m_home }}/alt-meza-ansible"
      # primary group
      group: wheel

  - name: Ensure user alt-meza-ansible .ssh dir configured
    file:
      path: "{{ m_home }}/alt-meza-ansible/.ssh"
      owner: alt-meza-ansible
      group: wheel
      mode: 0700
      state: directory

  - name: Copy meza-ansible keys to alt-meza-ansible
    copy:
      src: "{{ m_home }}/meza-ansible/.ssh/{{ item.name }}"
      dest: "{{ m_home }}/alt-meza-ansible/.ssh/{{ item.name }}"
      owner: alt-meza-ansible
      group: wheel
      mode: "{{ item.mode }}"
    with_items:
    - name: id_rsa
      mode: "0600"
    - name: id_rsa.pub
      mode: "0644"

  - name: Copy meza-ansible known_hosts to alt-meza-ansible
    copy:
      src: "{{ m_home }}/meza-ansible/.ssh/{{ item.name }}"
      dest: "{{ m_home }}/alt-meza-ansible/.ssh/{{ item.name }}"
      owner: alt-meza-ansible
      group: wheel
      mode: "{{ item.mode }}"
    ignore_errors: True
    with_items:
    - name: known_hosts
      mode: "0600"

  - name: Ensure secret.yml encrypted
    shell: >
      ansible-vault encrypt
      /opt/conf-meza/secret/{{ env }}/secret.yml
      --vault-password-file {{ m_home }}/meza-ansible/.vault-pass-{{ env }}.txt
    ignore_errors: True

  # Note: without this, the encryption above changes mode to 0600 and ownership
  # to root:root. This makes it impossible to include_vars later.
  - name: Ensure secret.yml owned by meza-ansible
    file:
      path: "/opt/conf-meza/secret/{{ env }}/secret.yml"
      owner: meza-ansible
      group: wheel
      mode: "0600"

# FIXME 800: Run against localhost
- hosts: app-servers
  become: yes
  roles:
    - set-vars
    - init-controller-config

# Ensure proper base setup on all servers in inventory, with the exception of
# servers in "exclude-all" group. At present, the intent of this group is to
# allow servers which serve as sources for database and user-uploaded files,
# but are not managed by this meza install.
- hosts: all:!exclude-all:!load-balancers-unmanaged
  become: yes
  roles:
    - set-vars
    - base
  tags: base

- hosts: load-balancers
  become: yes
  tags: load-balancer
  roles:
    - set-vars
    - role: firewalld
      firewalld_port: 8001
      firewalld_protocol: tcp
      firewalld_servers: "{{ groups['app-servers'] }}"
      firewalld_zone: "{{m_private_networking_zone|default('public')}}"
    - role: firewalld
      firewalld_port: 8081
      firewalld_protocol: tcp
      firewalld_servers: "{{ groups['parsoid-servers'] }}"
      firewalld_zone: "{{m_private_networking_zone|default('public')}}"
    # NOTE: firewalld ports 80 and 443 opened to ALL within haproxy role
    - haproxy

- hosts: app-servers
  become: yes
  tags: apache-php
  roles:
    - set-vars
    - role: firewalld
      # firewalld_service: http
      firewalld_port: 8080
      firewalld_protocol: tcp
      firewalld_servers: "{{ groups['load-balancers'] }}"
      firewalld_zone: "{{m_private_networking_zone|default('public')}}"
    - role: firewalld
      firewalld_port: 8080
      firewalld_protocol: tcp
      firewalld_servers: "{{ groups['load-balancers-unmanaged'] }}"
      firewalld_zone: "{{m_private_networking_zone|default('public')}}"
      when: "'load-balancers-unmanaged' in groups"
    - role: firewalld
      firewalld_port: 8080
      firewalld_protocol: tcp
      firewalld_servers: "{{ groups['parsoid-servers'] }}"
      firewalld_zone: "{{m_private_networking_zone|default('public')}}"
    - base-extras
    - imagemagick
    - apache-php

# Keeping this as a separate play, since at some point it will make sense to
# configure app-servers as gluster clients and have separate gluster servers
# (which can also be app-servers, of course, like everything else in meza)
- hosts: app-servers
  become: yes
  tags: gluster
  vars:
    gluster_replicas: "{{ groups['app-servers'] | length }}"
  roles:
    - set-vars

    # Portmap tcp and udp
    #
    # From docs:
    # ref: http://gluster.readthedocs.io/en/latest/Administrator%20Guide/Troubleshooting/?highlight=38465
    #
    # Check your firewall setting to open ports 111 for portmap
    # requests/replies and Gluster NFS server requests/replies. Gluster NFS
    # server operates over the following port numbers: 38465, 38466, and 38467.
    - role: firewalld
      firewalld_port: 111
      firewalld_protocol: tcp
      firewalld_servers: "{{ groups['app-servers'] }}"
      firewalld_zone: "{{m_private_networking_zone|default('public')}}"
      when: "groups['app-servers']|length|int > 1"
    - role: firewalld
      firewalld_port: 111
      firewalld_protocol: udp
      firewalld_servers: "{{ groups['app-servers'] }}"
      firewalld_zone: "{{m_private_networking_zone|default('public')}}"
      when: "groups['app-servers']|length|int > 1"

    # All gluster servers, Gluster Daemon
    # maybe also: 24009, 24010, 24011
    #
    # From the docs
    # ref: https://gluster.readthedocs.io/en/latest/Administrator%20Guide/Setting%20Up%20Clients/
    #
    # Ensure that TCP and UDP ports 24007 and 24008 are open on all Gluster
    # servers. Apart from these ports, you need to open one port for each brick
    # starting from port 49152 (instead of 24009 onwards as with previous
    # releases). The brick ports assignment scheme is now compliant with IANA
    # guidelines. For example: if you have five bricks, you need to have ports
    # 49152 to 49156 open.
    - role: firewalld
      firewalld_port: 24007
      firewalld_protocol: tcp
      firewalld_servers: "{{ groups['app-servers'] }}"
      firewalld_zone: "{{m_private_networking_zone|default('public')}}"
      when: "groups['app-servers']|length|int > 1"
    - role: firewalld
      firewalld_port: 24008
      firewalld_protocol: tcp
      firewalld_servers: "{{ groups['app-servers'] }}"
      firewalld_zone: "{{m_private_networking_zone|default('public')}}"
      when: "groups['app-servers']|length|int > 1"

    # One port required for each brick (in meza, this equals each server (one
    # brick per server))
    - role: firewalld
      firewalld_port: 49152
      firewalld_protocol: tcp
      firewalld_servers: "{{ groups['app-servers'] }}"
      firewalld_zone: "{{m_private_networking_zone|default('public')}}"
      when: "groups['app-servers']|length|int > 1"
    - role: firewalld
      firewalld_port: 49153
      firewalld_protocol: tcp
      firewalld_servers: "{{ groups['app-servers'] }}"
      firewalld_zone: "{{m_private_networking_zone|default('public')}}"
      when: "groups['app-servers']|length|int > 1"
    - role: firewalld
      firewalld_port: 49154
      firewalld_protocol: tcp
      firewalld_servers: "{{ groups['app-servers'] }}"
      firewalld_zone: "{{m_private_networking_zone|default('public')}}"
      when: "groups['app-servers']|length|int > 1"
    - role: firewalld
      firewalld_port: 49155
      firewalld_protocol: tcp
      firewalld_servers: "{{ groups['app-servers'] }}"
      firewalld_zone: "{{m_private_networking_zone|default('public')}}"
      when: "groups['app-servers']|length|int > 1"

    # FIXME #801: Some docs said ports 38465, 38466, 38467 needed for Gluster

    - role: gluster
      when: "groups['app-servers']|length|int > 1"


- hosts: memcached-servers
  become: yes
  tags: memcached
  roles:
    - set-vars
    - role: firewalld
      firewalld_port: 11211
      firewalld_protocol: tcp
      firewalld_servers: "{{ groups['app-servers'] }}"
      firewalld_zone: "{{m_private_networking_zone|default('public')}}"
    - memcached

- hosts: db-master
  become: yes
  tags: database
  roles:
    - set-vars
    - role: firewalld
      firewalld_service: mysql
      firewalld_servers: "{{ groups['app-servers'] }}"
      firewalld_zone: "{{m_private_networking_zone|default('public')}}"
    - role: firewalld
      firewalld_service: mysql
      firewalld_servers: "{{ groups['db-slaves'] }}"
      firewalld_zone: public
    - role: database
      # Get the one and only server that should be in the db-master group and set
      # it's IP address as replication master IP. Note that this can be left blank
      # or not included at all if no replication should be performed.
      # FIXME #802: Should replication master be set only if slaves exist?
      mysql_replication_master: "{{ groups['db-master'][0] }}"
      mysql_replication_role: master


- hosts: db-slaves
  become: yes
  tags: database
  roles:
    - set-vars
    - role: firewalld
      firewalld_service: mysql
      firewalld_servers: "{{ groups['app-servers'] }}"
      firewalld_zone: "{{m_private_networking_zone|default('public')}}"
    - role: database
      # Get the one and only server that should be in the db-master group and set
      # it's IP address as replication master IP. Note that this can be left blank
      # or not included at all if no replication should be performed.
      mysql_replication_master: "{{ groups['db-master'][0] }}"
      mysql_replication_role: slave


- hosts: elastic-servers
  become: yes
  tags: elasticsearch
  roles:
    - set-vars
    - role: firewalld
      firewalld_port: 9200
      firewalld_protocol: tcp
      firewalld_servers: "{{ groups['app-servers'] }}"
      firewalld_zone: "{{m_private_networking_zone|default('public')}}"
    - role: firewalld
      firewalld_port: 9300
      firewalld_protocol: tcp
      firewalld_servers: "{{ groups['app-servers'] }}"
      firewalld_zone: "{{m_private_networking_zone|default('public')}}"
    - role: firewalld
      firewalld_port: 9200
      firewalld_protocol: tcp
      firewalld_servers: "{{ groups['elastic-servers'] }}"
      firewalld_zone: "{{m_private_networking_zone|default('public')}}"
    - role: firewalld
      firewalld_port: 9300
      firewalld_protocol: tcp
      firewalld_servers: "{{ groups['elastic-servers'] }}"
      firewalld_zone: "{{m_private_networking_zone|default('public')}}"
    - elasticsearch

# Note: this is app-servers again, but must be after everything else is setup
- hosts: app-servers
  become: yes
  tags: mediawiki
  roles:
    - set-vars
    - htdocs
    - mediawiki


# Parsoid configuration moved after MediaWiki since Parsoid needs to know which
# wikis exist before writing localsettings.js and (re)starting the service
- hosts: parsoid-servers
  become: yes
  tags: parsoid
  roles:
    - set-vars
    # Allow app servers to get to parsoid server(s) on port 8000
    - role: firewalld
      firewalld_port: 8000
      firewalld_protocol: tcp
      firewalld_servers: "{{ groups['app-servers'] }}"
      firewalld_zone: "{{m_private_networking_zone|default('public')}}"
    - role: firewalld
      firewalld_port: 8000
      firewalld_protocol: tcp
      firewalld_servers: "{{ groups['load-balancers'] }}"
      firewalld_zone: "{{m_private_networking_zone|default('public')}}"
    - role: firewalld
      firewalld_port: 8000
      firewalld_protocol: tcp
      firewalld_servers: "{{ groups['load-balancers-unmanaged'] }}"
      firewalld_zone: "{{m_private_networking_zone|default('public')}}"
      when: "'load-balancers-unmanaged' in groups"
    - nodejs
    - parsoid
    - parsoid-settings

- hosts: logging-servers
  become: yes
  tags: logging
  roles:
    - set-vars
    - role: meza-log
      when: docker_skip_tasks is not defined or not docker_skip_tasks

- hosts: all:!exclude-all:!load-balancers-unmanaged
  become: yes
  tags:
    - cron
    - always
  roles:
    - set-vars
    - role: cron
      when: docker_skip_tasks is not defined or not docker_skip_tasks
 
