---
- name: Install php dependency packages
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - zlib-devel
    - sqlite-devel
    - bzip2-devel
    - pcre-devel
    - openssl-devel
    - curl-devel
    - libxml2-devel
    - libXpm-devel
    - gmp-devel
    - libicu-devel
    - t1lib-devel
    - aspell-devel
    - libcurl-devel
    - libjpeg-devel
    - libvpx-devel
    - libpng-devel
    - freetype-devel
    - readline-devel
    - libtidy-devel
    - libmcrypt-devel
    - pam-devel
    - sendmail
    - sendmail-cf
    - m4
    - xz-libs
    - mariadb-libs

- name: Get IUS repository
  include: ius.yml

- name: Ensure PHP IUS packages installed
  yum:
    name: "{{item}}"
    state: installed
  with_items:
    - php56u
    - php56u-cli
    - php56u-common
    - php56u-devel
    - php56u-gd
    - php56u-pecl-memcache
    - php56u-pspell
    - php56u-snmp
    - php56u-xml
    - php56u-xmlrpc
    - php56u-mysqlnd
    - php56u-pdo
    - php56u-odbc
    - php56u-pear
    - php56u-pecl-jsonc
    - php56u-process
    - php56u-bcmath
    - php56u-intl
    - php56u-opcache
    - php56u-soap
    - php56u-mbstring
    - php56u-mcrypt
    - php56u-mssql

- name: Write php.ini file
  template:
    src: php.ini.j2
    dest: "{{ m_php_ini }}"
  notify:
  - restart apache

- name: Write freetds.conf file
  template:
    src: freetds.conf.j2
    dest: /etc/freetds.conf
  notify:
  - restart apache

- name: Ensure PEAR Mail and Net_SMTP packages installed
  pear:
    name: "{{ item }}"
    state: latest
  tags:
  - latest
  with_items:
  - Mail
  - Net_SMTP
