---

- name: Set meza-core path variables
  include_vars:
    file: /opt/meza/config/core/defaults.yml

- name: If using gluster (app-servers > 1), override m_uploads_dir
  set_fact:
    m_uploads_dir: "{{ gluster_mount_dir }}"
  when: "'app-servers' in groups and groups['app-servers']|length|int > 1"

- name: Set meza local public variables
  include_vars:
    file: "{{ m_local_public }}/public.yml"
  # Ingore errors so this file is not required to be included
  ignore_errors: yes

- name: Get individual wikis dirs from localhost
  find:
    paths: "{{ m_local_public }}/wikis/"
    file_type: directory
  register: wikis_dirs
  delegate_to: localhost
  run_once: yes

- set_fact:
    list_of_wikis: "{{ wikis_dirs.files | map(attribute='path') | map('basename') | list }}"

- name: "Set meza environment-specific public variables for env={{ env }}"
  include_vars:
    file: "{{ m_local_public }}/env/{{ env }}.yml"
  # Ingore errors so this file is not required to be included
  ignore_errors: yes

- name: Set meza local secret variables
  include_vars:
    file: "{{ m_local_secret }}/{{ env }}/secret.yml"
  # DO NOT ingore errors generally, except when setting up an env
  ignore_errors: "{{ allow_missing_secret_config | default(false) }}"
